export const RECEIVE_CHECKOUT_DETAILS = 'RECEIVE_CHECKOUT_DETAILS'
export const SET_PRODUCT = 'SET_PRODUCT'

export const SET_VARIANTS = 'SET_VARIANTS' // ??
export const SELECT_DATE = 'SELECT_DATE'
export const SELECT_TIMESLOT = 'SELECT_TIMESLOT'
export const SELECT_VARIANT = 'SELECT_VARIANT'
export const INVALIDATE_DATE = 'INVALIDATE_DATE'

export const FETCH_VARIANTS = 'FETCH_VARIANTS'
export const REQUEST_VARIANTS = 'REQUEST_VARIANTS'
export const RECEIVE_VARIANTS_SUCCESS = 'RECEIVE_VARIANTS_SUCCESS'
export const RECEIVE_VARIANTS_FAILURE = 'RECEIVE_VARIANTS_FAILURE'

export const FETCH_TIMESLOTS = 'FETCH_TIMESLOTS'
export const REQUEST_TIMESLOTS = 'REQUEST_TIMESLOTS'
export const RECEIVE_TIMESLOTS_SUCCESS = 'RECEIVE_TIMESLOTS_SUCCESS'
export const RECEIVE_TIMESLOTS_FAILURE = 'RECEIVE_TIMESLOTS_FAILURE'
export const PRESELECT_CHECKOUT_DETAILS = 'PRESELECT_CHECKOUT_DETAILS'
