export const RECEIVE_CHECKOUT_DETAILS = 'RECEIVE_CHECKOUT_DETAILS'

export const SELECT_DATE = 'SELECT_DATE'
export const INVALIDATE_DATE = 'INVALIDATE_DATE'

export const FETCH_TIMESLOTS = 'FETCH_TIMESLOTS'
export const RECEIVE_TIMESLOTS = 'RECEIVE_TIMESLOTS'
export const SELECT_TIMESLOT = 'SELECT_TIMESLOT'

export const ADD_VARIANT = 'ADD_VARIANT'